CREATE TABLE "Events" (
  "eventID" integer,
  "eventName" string,
  "organizerID" integer,
  "eventType" string,
  "startTime" timestamp,
  "endTime" timestamp,
  "location" string,
  "maxParticipants" integer,
  "currentParticipants" integer,
  "eventPrices" integer
);

CREATE TABLE "Booking" (
  "bookingID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "eventID" integer,
  "studentID" integer,
  "bookingTime" timestamp,
  "paymentStatus" string
);

CREATE TABLE "Organizer" (
  "organizerID" integer,
  "organizerUserName" string,
  "organizerPassword" string
);

CREATE TABLE "Student" (
  "studentID" integer,
  "studentUserName" string,
  "studentPassword" string
);

CREATE TABLE "Admin" (
  "adminID" integer,
  "adminUserName" string,
  "adminPassword" string
);

ALTER TABLE "Booking" ADD FOREIGN KEY ("eventID") REFERENCES "Events" ("eventID");

ALTER TABLE "Booking" ADD FOREIGN KEY ("studentID") REFERENCES "Student" ("studentID");

ALTER TABLE "Events" ADD FOREIGN KEY ("organizerID") REFERENCES "Organizer" ("organizerID");
