
CREATE TABLE "Events" (
                          "eventID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "eventName" VARCHAR(255) NOT NULL,
                          "organizerID" INTEGER NOT NULL,
                          "eventType" VARCHAR(100),
                          "startTime" TIMESTAMP NOT NULL,
                          "endTime" TIMESTAMP NOT NULL,
                          "location" VARCHAR(255),
                          "maxParticipants" INTEGER NOT NULL,
                          "currentParticipants" INTEGER DEFAULT 0,
                          "eventPrices" INTEGER NOT NULL,
                          CONSTRAINT fk_events_organizer
                              FOREIGN KEY ("organizerID")
                                  REFERENCES "Organizer" ("organizerID")
);


CREATE TABLE "Booking" (
                           "bookingID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "eventID" INTEGER NOT NULL,
                           "studentID" INTEGER NOT NULL,
                           "bookingTime" TIMESTAMP NOT NULL,
                           "paymentStatus" VARCHAR(50),
                           CONSTRAINT fk_booking_event
                               FOREIGN KEY ("eventID")
                                   REFERENCES "Events" ("eventID"),
                           CONSTRAINT fk_booking_student
                               FOREIGN KEY ("studentID")
                                   REFERENCES "Student" ("studentID")
);


CREATE TABLE "Organizer" (
                             "organizerID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "organizerUserName" VARCHAR(255) UNIQUE NOT NULL,
                             "organizerPassword" VARCHAR(255) NOT NULL
);


CREATE TABLE "Student" (
                           "studentID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "studentUserName" VARCHAR(255) UNIQUE NOT NULL,
                           "studentPassword" VARCHAR(255) NOT NULL
);

CREATE TABLE "Admin" (
                         "adminID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "adminUserName" VARCHAR(255) UNIQUE NOT NULL,
                         "adminPassword" VARCHAR(255) NOT NULL
);